Repository Project-Babble/ProjectBabble, pull requests merged in 2025-05, with the labels that each got.

#108 Fix: "AttributeError: NoneType" exception when closing
  BabbleApp/logger.py
Labels: bug

#115 Fix: "One euro filter return none" by Fracas42
  BabbleApp/one_euro_filter.py
Labels: bug

#111 Feat: Optional logging
  BabbleApp/Locale/Afrikaans/locale.json
  BabbleApp/Locale/Dansk/locale.json
  BabbleApp/Locale/Deutsch/locale.json
  BabbleApp/Locale/English/locale.json
  BabbleApp/Locale/Español/locale.json
  BabbleApp/Locale/Française/locale.json
  BabbleApp/Locale/Indonesian/locale.json
  BabbleApp/Locale/Italiano/locale.json
  BabbleApp/Locale/Nederlands/locale.json
  BabbleApp/Locale/OwO/locale.json
  BabbleApp/Locale/Pirate Speak/locale.json
  BabbleApp/Locale/Polski/locale.json
  BabbleApp/Locale/Pусский/locale.json
  BabbleApp/Locale/Svenska/locale.json
  BabbleApp/Locale/简体中文/locale.json
  BabbleApp/Locale/繁體中文/locale.json
  BabbleApp/babbleapp.py
  BabbleApp/config.py
  BabbleApp/general_settings_widget.py
Labels: enhancement

#109 Fix: Clean notifier's remains
  BabbleApp/Locale/Afrikaans/locale.json
  BabbleApp/Locale/Dansk/locale.json
  BabbleApp/Locale/Deutsch/locale.json
  BabbleApp/Locale/English/locale.json
  BabbleApp/Locale/Español/locale.json
  BabbleApp/Locale/Française/locale.json
  BabbleApp/Locale/Indonesian/locale.json
  BabbleApp/Locale/Italiano/locale.json
  BabbleApp/Locale/Nederlands/locale.json
  BabbleApp/Locale/OwO/locale.json
  BabbleApp/Locale/Pirate Speak/locale.json
  BabbleApp/Locale/Polski/locale.json
  BabbleApp/Locale/Pусский/locale.json
  BabbleApp/Locale/Svenska/locale.json
  BabbleApp/Locale/简体中文/locale.json
  BabbleApp/Locale/繁體中文/locale.json
  BabbleApp/requirements.txt
Labels: enhancement

#110 Fix: Use rotating log file w/2MB limit, changed file name 'n removed...
  BabbleApp/logger.py
Labels: enhancement

#118 Update README.md
  README.md
Labels: documentation, enhancement

#113 Fix: Missing serial port after list refresh...
  BabbleApp/utils/misc_utils.py
Labels: bug

#112 Fix: Throttle serial connection retries
  BabbleApp/camera.py
Labels: enhancement

#120 feat(PR) Cleanup files for Post-PR mergers
  BabbleApp/camera.py
  BabbleApp/camera_widget.py
  BabbleApp/utils/misc_utils.py
Labels: enhancement
